config/routes.rb
Dealio::Application.routes.draw do
  root 'deals#index'

  resources :deals

end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

	def index
		@deals = Deal.all
	end	

	def new
		@deal = Deal.new
	end	

	def create
		Deal.create(deal_params) 
		redirect_to root_path
	end	

	private

  	def deal_params
    	params.require(:deal).permit(:sale, :description, :address)
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/index.html.erb
<br />
<br class="clear" />
	<div class="container-box col-xs-6 col-xs-offset-1">	
			<%= link_to 'I/O DEAL', new_deal_path(@deal), :class => 'btn-xl btn-danger center' %>
	<br />		
	<br />
	<br />	
	
		<h2>Recent Deal i/o</h2>
		<br />
	</div>	
<% @deals.each do |deal| %>

		<div class="booyah-box col-xs-8 col-xs-offset-1">		
				
					<h1><%= deal.sale %></h1><br/>
					<i><%= deal.address %></i><br />
					<p><%= deal.description %></p><br />
					
				
		</div>
	<% end %>

<br class="clear" />

app/views/deals/new.html.erb
<%= simple_form_for @deal do |f| %>
	<div class="box-one col-xs-10 col-xs-offset-1">
	  <h1>What's da Dealio?</h1>
	  <br />

			    <%= f.input :sale %>
			    <%= f.input :address %>
			    <%= f.input :description %>
			
	    <br />
	    <%= f.submit 'Deal it!', :class => 'btn btn-default' %>
		</div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
     </a><%= link_to 'DEAL I/O Exchange', root_path, :class => 'navbar-brand' %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">    
        <li><a href="https://github.com/sebtn/dealio">..By Seb</a></li>
      </ul> 
      <!--! <ul class="nav navbar-nav navbar-right">
        <li><a href="#">SHARE DEALiO</a></li> -->
        </li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <br />
</nav> 

	<div class="jumbotron text-center">
	  <h1>Deal i/o  </h1>
    <div class="j.text col-xs-10 col-xs-offset-1">
	  <!-- <p>Share hot spots on deals on the fly and make your life a litte bit smarter it will allow to save money on those little things... form groups and share with everyone you know, family and friends</p> -->
    <b><p>Barter and trade</p></b>

	 </div> 
  </div> 

	   
<%= yield %>

</body>
</html>